# Generated by Django 5.1.15 on 2026-03-10 05:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('danger_score', models.FloatField(default=0.0, help_text='0-100 danger score')),
                ('hazard_count', models.IntegerField(default=0)),
                ('route_data', models.JSONField(blank=True, default=dict, help_text='Polyline/waypoints from map provider')),
                ('map_provider', models.CharField(default='stub', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'route_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
