# Generated by Django 5.1.15 on 2026-03-10 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalFootprintScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('identity_score', models.IntegerField(default=0, help_text='0-100 integrity score')),
                ('deepfake_score', models.FloatField(default=0.0, help_text='ML deepfake probability (0-1)')),
                ('flagged_urls', models.JSONField(blank=True, default=list)),
                ('breaches_found', models.JSONField(blank=True, default=list)),
                ('scan_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'digital_footprint_scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flagged_url', models.URLField()),
                ('platform_name', models.CharField(blank=True, max_length=100)),
                ('breach_type', models.CharField(blank=True, max_length=50)),
                ('notice_text', models.TextField(blank=True)),
                ('notice_pdf_url', models.URLField(blank=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='privacy.digitalfootprintscan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'privacy_notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
