# Generated by Django 5.1.15 on 2026-03-10 05:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardPin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('hazard_type', models.CharField(choices=[('broken_streetlight', 'Broken Streetlight'), ('harassment', 'Harassment Hotspot'), ('suspicious_activity', 'Suspicious Activity'), ('unsafe_road', 'Unsafe Road'), ('construction', 'Construction Zone'), ('flooding', 'Flooding'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('upvoted_by', models.ManyToManyField(blank=True, related_name='upvoted_hazards', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_pins', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hazards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hazard_pins',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hazard_type', 'is_active'], name='hazard_pins_hazard__43c21d_idx')],
            },
        ),
    ]
