# Generated by Django 5.1.15 on 2026-03-10 05:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('manual_sos', 'Manual SOS'), ('scream_detection', 'Scream Detection'), ('duress_pin', 'Duress PIN'), ('offline_fallback', 'Offline Fallback'), ('shake_gesture', 'Shake Gesture')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dispatched', 'Dispatched'), ('responding', 'Responding'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('false_alarm', 'False Alarm')], default='active', max_length=15)),
                ('start_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('notes', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_emergencies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_events',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emergency.emergencyevent')),
            ],
            options={
                'db_table': 'emergency_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emergencyevent',
            index=models.Index(fields=['status', '-started_at'], name='emergency_e_status_6b938c_idx'),
        ),
    ]
